apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: adityamandil317/multi-web-httpd:latest
    ports:
      - containerPort: 80
        name: first
      - containerPort: 8080
        name: second
        
---
apiVersion: v1
kind: Service
metadata:
  name: first
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: first-port
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: second
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: second-port
    protocol: TCP
    port: 80
    targetPort: 8080
